### ISSUE TITLE
support multiple build images

### ISSUE THREAD

**Issue by cseed** [hail-is/ci#3]
To support building of repos other than hail.

Short-term solution: hard code build images based on target_url?

Long-term solution: the CI merges the source_ref onto the target_ref and uses the resulting configuration file.  This configuration file can be be used for additional things, e.g., configuring how to update PR checks.

**Comment by danking** [comment]
build images are now supported by the `hail-ci-build-image` file. it does the long-term solution, though the config only contains an image name.
